# Generated by Django 5.2.1 on 2025-09-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_notes_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='text',
            field=models.TextField(max_length=1250, verbose_name='Текст'),
        ),
    ]
