# Generated by Django 5.1.7 on 2025-09-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_notes_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='text',
            field=models.TextField(max_length=2000, verbose_name='Текст'),
        ),
    ]
